title: QuaSi Software
email: quasi-software@siz-energieplus.de
description: >- # this means to ignore newlines until "baseurl:"
  News, contacts and other information on the QuaSi project.
baseurl: ""
url: "http://quasi-software.org"

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.md
